import oracledb

class ConexionOracle:
    """
        Clase para conexion de BD.
    """
    def __init__(self, usuario: str, password: str, url: str):
        self.usuario = usuario
        self.password = password
        self.url = url
        self.connection = None

    def conectar(self):
        """
            Genera la conexión con la bd según datos recibidos.\n
        """
        try:
            self.connection = oracledb.connect(
                user=self.usuario,
                password=self.password,
                dsn=self.url
            )
            print("[INFO]: Conectado a BD correctamente.")
            
        except oracledb.DatabaseError as e:
            error, = e.args
            print(f"[ERROR]: No se pudo conectar a BD → {error.message}")

    def desconectar(self):
        """
            Si es que hay una conexión activa, la finaliza.
        """
        if self.connection:
            self.connection.close()
            print("[INFO]: Conexión a BD cerrada correctamente.")

    def obtener_cursor(self):
        """
            Genera el cursor para BD.
        """
        if not self.connection:
            self.conectar()

        return self.connection.cursor()
    
def validar_tablas(db):
    """
        Se encarga de crear la tablas en caso de que estas no existan.
    """

    sql_usuario = """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE rr_usuario (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                        nombre_usuario VARCHAR2(60) UNIQUE,
                        clave VARCHAR2(255),
                        nombre VARCHAR2(100),
                        apellido VARCHAR2(100),
                        fecha_nacimiento DATE,
                        telefono NUMBER,
                        email VARCHAR2(100),
                        tipo VARCHAR2(20),

                        CONSTRAINT pk_usuario PRIMARY KEY (id)
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
        """
    
    sql_paciente = """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE rr_paciente (
                        id_paciente NUMBER PRIMARY KEY,
                        comuna VARCHAR2(100),
                        fecha_primera_visita DATE,
                        
                        CONSTRAINT fk_paciente_usuario FOREIGN KEY (id_paciente) REFERENCES rr_usuario(id)
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
        """
    
    sql_medico = """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE rr_medico (
                        id_medico NUMBER PRIMARY KEY,
                        especialidad VARCHAR2(100),
                        horario_atencion VARCHAR2(100),
                        fecha_ingreso DATE,

                        CONSTRAINT fk_medico_usuario FOREIGN KEY (id_medico) REFERENCES rr_usuario(id)
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
        """

    sql_insumos = """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE rr_insumos (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                        nombre VARCHAR2(100),
                        tipo VARCHAR2(50),
                        stock NUMBER,

                        CONSTRAINT pk_insumos PRIMARY KEY (id)
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
        """

    sql_recetas = """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE rr_recetas (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                        id_paciente NUMBER,
                        id_medico NUMBER,
                        descripcion VARCHAR2(500),

                        CONSTRAINT pk_recetas PRIMARY KEY (id),
                        CONSTRAINT fk_recetas_paciente FOREIGN KEY (id_paciente) REFERENCES rr_paciente(id_paciente),
                        CONSTRAINT fk_recetas_medico FOREIGN KEY (id_medico) REFERENCES rr_medico(id_medico)
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
        """
    sql_consultas = """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE rr_consultas (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                        id_paciente NUMBER,
                        id_medico NUMBER,
                        id_receta NUMBER,
                        fecha DATE,
                        comentarios VARCHAR2(500),


                        CONSTRAINT pk_consultas PRIMARY KEY (id),
                        CONSTRAINT fk_consultas_paciente FOREIGN KEY (id_paciente) REFERENCES rr_paciente(id_paciente),
                        CONSTRAINT fk_consultas_medico FOREIGN KEY (id_medico) REFERENCES rr_medico(id_medico),
                        CONSTRAINT fk_consultas_receta FOREIGN KEY (id_receta) REFERENCES rr_recetas(id)
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
        """
    sql_agenda = """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE rr_agenda (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                        id_paciente NUMBER,
                        id_medico NUMBER,
                        fecha_consulta DATE,
                        estado VARCHAR2(20),

                        CONSTRAINT pk_agenda PRIMARY KEY (id),
                        CONSTRAINT fk_agenda_paciente FOREIGN KEY (id_paciente) REFERENCES rr_paciente(id_paciente),
                        CONSTRAINT fk_agenda_medico FOREIGN KEY (id_medico) REFERENCES rr_medico(id_medico)
                    )
                ';
            EXCEPTION  
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
                    """
    
    cursor = db.obtener_cursor()

    sentencias = [
        sql_usuario,
        sql_paciente,
        sql_medico,
        sql_insumos,
        sql_recetas,
        sql_consultas,
        sql_agenda
        
    ]

    try:
        for sql in sentencias:
            cursor.execute(sql)

        db.connection.commit()

        print("[INFO]: Tablas validadas/creadas correctamente")
    except Exception as e:
        db.connection.rollback()

        print("[ERROR]: Error al crear tablas:", e)
    finally:
        if cursor:
            cursor.close()
            